### ISSUE TITLE
url_1 = require("url") seems too be pulling in the legacy URL api

### ISSUE THREAD

**Issue by mikenowakme** [samiahmedsiddiqui/remarkable-external-link#4]
If I remove this line and just use URL(...) instead of url_1.URL(...) in your code, I get the new URL API from node. Any thought on what might be causing this?

**Comment by samiahmedsiddiqui** [comment]
@mikenowakme I am using the same thing, please refer to the source file.
https://github.com/samiahmedsiddiqui/remarkable-external-link/blob/master/src/index.ts#L18

`url_1` is coming in the compiled version. Can I ask what exactly the issue you are facing?

**Comment by vipzhicheng** [comment]
seems you create your package under node env, but if I want to use it in frontend, it will throw errors, the problem is that there is no 'url' object in browser env. but I found there is URL directly in node env and browser env, so I guess, you may not need to use:

```
import { URL } from 'url'
```
